version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
    environment:
      - TELEGRAM_TOKEN=your_telegram_bot_token_here
      - MONGO_URI=mongodb://mongo:27017/your_database_name
    depends_on:
      - mongo
    command: python -u bot.py

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=telegram_bot_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: